---
engines:
 remark-lint:
   enabled: true
   exclude_paths:
     - config/engines.yml
 cppcheck:
   enabled: true
   exclude_paths:
    - config/engines.yml
 duplication:
   enabled: true
   exclude_paths:
     - config/engines.yml
 metrics:
   enabled: true
   exclude_paths:
     - config/engines.yml
 coverage:
   enabled: true
   exclude_paths:
     - config/engines.yml
exclude_paths:
  - '.*releases?/.*'
  - '.*builds'
  - '.idea/*'
  - '.idea/**'
  - 'Libs/**'
  - 'Data/**'
  - 'Tools/**'
  - '.*'